name: tashil_agary
description: tashil_agary project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1 #flutter sdk 3.10.5

environment:
#  sdk: '>=2.18.5 <3.0.0'
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_messaging: ^14.7.1
  firebase_analytics: ^10.6.1
  firebase_core: ^2.19.0
  flutter_local_notifications: ^12.0.4
  firebase_auth: ^4.11.1
  firebase_dynamic_links: ^5.4.1
  cloud_firestore: ^4.11.0

  google_sign_in: ^5.4.4
  flutter_login_facebook: ^1.7.0
  sign_in_with_apple: ^4.3.0
  file_picker: ^5.2.10
#  firebase_storage: ^11.3.1





  provider: ^6.0.3
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  http: ^0.13.5

  easy_localization: ^3.0.3
#  overlay_support: ^2.0.1
#  pin_code_fields: ^7.4.0
#  flutter_zoom_drawer: ^3.0.0
  flutter_spinkit: ^5.1.0
  dropdown_plus: ^0.0.9



 
  shared_preferences: ^2.0.5
  cached_network_image: 3.2.1

  flutter_animated_dialog: ^2.0.0

  google_fonts: ^4.0.4
  intl: ^0.18.0
  page_transition: ^2.0.5
  bot_toast: ^4.0.2
#  curved_navigation_bar: ^1.0.3
  badges: ^2.0.2
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
#  modal_bottom_sheet: ^2.0.1
#  avatar_glow: ^2.0.2
  flutter_widget_from_html: ^0.8.5
  path_provider: ^2.0.11
  url_launcher: ^6.1.3
  share_plus: ^4.0.7
  whatsapp_unilink: ^2.0.1+1
#  sms_autofill: ^2.2.0
  image_picker: ^0.8.5+3
  flutter_svg: ^1.1.0
  connectivity_plus: ^2.3.5
#  launch_review: ^3.0.1
  map_launcher: ^2.5.0+1
  geolocator: ^10.1.0
#  scrollable_list_tab_scroller: ^1.1.0
  scrollable_positioned_list: ^0.3.6
  im_animations: ^0.1.2

  google_maps_flutter: ^2.2.2
  maps_toolkit: ^2.0.1
  location: ^5.0.3
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_api_headers: ^1.1.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_polyline_points: ^1.0.0
  dotted_border: ^2.1.0
  animated_bottom_navigation_bar: ^1.3.0
  rate: ^0.0.1

#  geocoding: ^2.0.5
#  flutter_geocoder: ^0.2.2-nullsafety
#  google_places_picker_advance: ^0.0.18

  sms_autofill: ^2.2.0
  pin_code_fields: ^7.4.0
  dropdown_button2: ^2.1.4
  nepali_date_picker: ^5.3.3
  lottie: ^2.3.2
  image: ^3.0.1
  photo_view: ^0.14.0
  widget_to_marker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_swipe_action_cell: ^3.1.3
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/svg/
   - assets/translations/
   - assets/developImages/
   - assets/celebrate.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
