name: tashil_agary
description: tashil_agary project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  flutter : 3.22.2
  sdk: '>=3.4.3 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_messaging:
  firebase_analytics:
  firebase_core:
  flutter_local_notifications:
  firebase_auth:
  firebase_dynamic_links:
  cloud_firestore:
  google_sign_in:
  flutter_login_facebook:
  sign_in_with_apple:
  file_picker:
  #  google_maps_cluster_manager: ^3.1.0
  #  firebase_storage: ^11.3.1





  provider:
  dio:
  dio_http_cache:
  http:

  easy_localization:
  #  overlay_support: ^2.0.1
  #  pin_code_fields: ^7.4.0
  #  flutter_zoom_drawer: ^3.0.0
  flutter_spinkit:
  dropdown_plus:




  shared_preferences:
  cached_network_image:
  flutter_animated_dialog_updated:
  #  flutter_animated_dialog:
  google_fonts:
  intl:
  page_transition:
  bot_toast:
  #  curved_navigation_bar: ^1.0.3
  badges:
  font_awesome_flutter:
  carousel_slider:
  #  modal_bottom_sheet: ^2.0.1
  #  avatar_glow: ^2.0.2
  flutter_widget_from_html:
  path_provider:
  url_launcher:
  share_plus:
  whatsapp_unilink:
  #  sms_autofill: ^2.2.0
  image_picker:
  flutter_svg:
  connectivity_plus:
  #  launch_review: ^3.0.1
  map_launcher:
  geolocator:
  #  scrollable_list_tab_scroller: ^1.1.0
  scrollable_positioned_list:
  im_animations:
  google_maps_flutter:
  maps_toolkit:
  location:
  flutter_google_places_hoc081098:
  google_api_headers:
  google_maps_webservice:
  flutter_polyline_points:
  dotted_border:
  animated_bottom_navigation_bar:
  rate:
  circle_progress_bar:

  #  geocoding: ^2.0.5
  #  flutter_geocoder: ^0.2.2-nullsafety
  #  google_places_picker_advance: ^0.0.18

  #  sms_autofill: ^2.2.0
  pin_code_fields:
  dropdown_button2:
  nepali_date_picker:
  #  lottie:
  image:
  photo_view:
  widget_to_marker:
  permission_handler:
#  flutter_swipe_action_cell: ^3.1.3
  flutter_linkify:
#  flutter_map:
#  latlong2:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/
    - assets/developImages/
    - assets/celebrate.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
